name: Build & Test
on:
  push:
  pull_request:
  release:
    types:
      - published
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Project name to pack and publish
  PROJECT_NAME: StrykerDemo
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          
      - name: Restore
        run: dotnet restore
        working-directory: src
        
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: src
        
      - name: Run Unit Tests
        run: dotnet test -c Release --logger:"nunit;LogFilePath=test-result.xml"
        working-directory: src

      - name: Publish Unit Tests Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: |
            **\test-result.xml

      - name: Install dotnet tools
        working-directory: src
        run: dotnet tool restore
    
      - name: Run Stryker.NET
        working-directory: src/StrykerDemo.Tests
        run: dotnet stryker --reporter "markdown" --reporter "html" --reporter "progress"

      - name: Upload Stryker Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: src/StrykerDemo.Tests/StrykerOutput/**/reports/mutation-report.html
          retention-days: 5

      - name: Add Stryker report to Job Summary
        run: | 
          $content = Get-Content src/StrykerDemo.Tests/StrykerOutput/*/reports/mutation-report.md
          $content >> $env:GITHUB_STEP_SUMMARY
          echo ("STRYKER_REPORT=" + $content) | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Debug
        run: | 
           echo $STRYKER_REPORT
          
      #- name: Post Stryker report as PR comment
      #  uses: marocchino/sticky-pull-request-comment@v2
      #  with:
      #    message: `
      #  if: github.event_name == 'pull_request'
